server:
  port: 8080
eureka:
  instance:
#    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  cloud:
    gateway:
      mvc:
        routes:
          - id: user-service
            uri: lb://user-service
            predicates:
              - Path=/users/**
          - id: car-service
            uri: lb://car-service
            predicates:
              - Path=/cars/**
          - id: bike-service
            uri: lb://bike-service
            predicates:
              - Path=/bikes/**
      discovery:
        locator:
          enabled: true
