server:
  port: 8080

eureka:
  instance:
#    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**
          filters:
            - RewritePath=/users, /v1/users
        - id: car-service
          uri: lb://car-service
          predicates:
            - Path=/cars/**
          filters:
            - RewritePath=/cars, /v1/cars
        - id: bike-service
          uri: lb://bike-service
          predicates:
            - Path=/bikes/**
          filters:
            - RewritePath=/bikes, /v1/bikes
